### ISSUE TITLE
cabal build problems

### ISSUE THREAD

**Issue by agreif** [agocorona/hplayground#11]
hi,

cabal installs haste-compile 0.5.4 fine, but then

Configuring haste-perch-0.1.0.9...
Building haste-perch-0.1.0.9...
Failed to install haste-perch-0.1.0.9
Build log ( /home/agreif/project/hplay1/.cabal-sandbox/logs/haste-perch-0.1.0.9.log ):
Configuring haste-perch-0.1.0.9...
Building haste-perch-0.1.0.9...
Preprocessing library haste-perch-0.1.0.9...

Haste/Perch.hs:17:15: Warning:
    -XOverlappingInstances is deprecated: instead use per-instance pragmas OVERLAPPING/OVERLAPPABLE/OVERLAPS

Haste/App/Perch.hs:18:15: Warning:
    -XOverlappingInstances is deprecated: instead use per-instance pragmas OVERLAPPING/OVERLAPPABLE/OVERLAPS
[1 of 2] Compiling Haste.App.Perch  ( Haste/App/Perch.hs, dist/dist-sandbox-bd4b01fe/build/Haste/App/Perch.o )

Haste/App/Perch.hs:61:15: Not in scope: `newTextElem'

Haste/App/Perch.hs:71:9:
    Not in scope: `setAttr'
    Perhaps you meant `jsSetAttr' (imported from Haste.App)

Haste/App/Perch.hs:76:15:
    Not in scope: `newElem'
    Perhaps you meant one of these:
      `nelem' (line 75), `notElem' (imported from Prelude)

Haste/App/Perch.hs:94:17: Not in scope: `setProp'

Haste/App/Perch.hs:97:13:
    Not in scope: type constructor or class `ClientCallback'

Haste/App/Perch.hs:97:42:
    Not in scope: type constructor or class `Event'

Haste/App/Perch.hs:100:15: Not in scope: `evtName'

Haste/App/Perch.hs:101:13:
    Not in scope: `getAttr'
    Perhaps you meant `getAlt' (imported from Data.Monoid)

Haste/App/Perch.hs:105:9: Not in scope: `onEvent'

Haste/App/Perch.hs:106:9:
    Not in scope: `setAttr'
    Perhaps you meant `jsSetAttr' (imported from Haste.App)
cabal: user error (Error: some packages failed to install:
haste-perch-0.1.0.9 failed during the building phase. The exception was:
ExitFailure 1
hplay1-0.1.0.0 depends on haste-perch-0.1.0.9 which failed to install.
hplayground-0.1.3.1 depends on haste-perch-0.1.0.9 which failed to install.
)

any ideas?

thansk,
Alex.

**Comment by agocorona** [comment]
Hi Alex, unfortunately it does not work with the last version of Haste. Use
Haste-0.3.xxx.

We are busy integrating it with transient and ghcjs, which result in a very
powerful client-server architecture.

2016-02-28 14:19 GMT+01:00 Alex Greif <notifications@github.com>:

> hi,
>
> cabal installs haste-compile 0.5.4 fine, but then
>
> Configuring haste-perch-0.1.0.9...
> Building haste-perch-0.1.0.9...
> Failed to install haste-perch-0.1.0.9
> Build log (
> /home/agreif/project/hplay1/.cabal-sandbox/logs/haste-perch-0.1.0.9.log ):
> Configuring haste-perch-0.1.0.9...
> Building haste-perch-0.1.0.9...
> Preprocessing library haste-perch-0.1.0.9...
>
> Haste/Perch.hs:17:15: Warning:
> -XOverlappingInstances is deprecated: instead use per-instance pragmas
> OVERLAPPING/OVERLAPPABLE/OVERLAPS
>
> Haste/App/Perch.hs:18:15: Warning:
> -XOverlappingInstances is deprecated: instead use per-instance pragmas
> OVERLAPPING/OVERLAPPABLE/OVERLAPS
> [1 of 2] Compiling Haste.App.Perch ( Haste/App/Perch.hs,
> dist/dist-sandbox-bd4b01fe/build/Haste/App/Perch.o )
>
> Haste/App/Perch.hs:61:15: Not in scope: `newTextElem'
>
> Haste/App/Perch.hs:71:9:
> Not in scope: setAttr'
> Perhaps you meantjsSetAttr' (imported from Haste.App)
>
> Haste/App/Perch.hs:76:15:
> Not in scope: newElem'
> Perhaps you meant one of these:
> nelem' (line 75), `notElem' (imported from Prelude)
>
> Haste/App/Perch.hs:94:17: Not in scope: `setProp'
>
> Haste/App/Perch.hs:97:13:
> Not in scope: type constructor or class `ClientCallback'
>
> Haste/App/Perch.hs:97:42:
> Not in scope: type constructor or class `Event'
>
> Haste/App/Perch.hs[image: :100:]15: Not in scope: `evtName'
>
> Haste/App/Perch.hs:101:13:
> Not in scope: getAttr'
> Perhaps you meantgetAlt' (imported from Data.Monoid)
>
> Haste/App/Perch.hs:105:9: Not in scope: `onEvent'
>
> Haste/App/Perch.hs:106:9:
> Not in scope: setAttr'
> Perhaps you meantjsSetAttr' (imported from Haste.App)
> cabal: user error (Error: some packages failed to install:
> haste-perch-0.1.0.9 failed during the building phase. The exception was:
> ExitFailure 1
> hplay1-0.1.0.0 depends on haste-perch-0.1.0.9 which failed to install.
> hplayground-0.1.3.1 depends on haste-perch-0.1.0.9 which failed to install.
> )
>
> any ideas?
>
> thansk,
> Alex.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agocorona/hplayground/issues/11>.
>



-- 
Alberto.
