### ISSUE TITLE
Question : how wake works

### ISSUE THREAD

**Issue by juicelink** [agocorona/hplayground#8]
Hi,

when I set console traces in todomvc exemple, I can see two different behaviors for the wake function

in the newtodo function :
```
newTodo= do
      let entry= boxCell "new-todo"
      task <- mk entry Nothing `wake` OnChange
```
code after the wake line run only when the OnChange event is triggered

in the toggleActive function:
```
 toggleActive = do
        Just (task,st) <- getTask idtask
        let checked= case st of Completed -> True; Active -> False
        let ch = setCheckBox checked "check" `wake` OnClick ! atr "class" "toggle"
```
code after the  the wake line is executed on Onclick event, but also the first time the function is called

I can't figure why it differs and how to have the  same behavior as in newtodo function (to avoid redondant local storage updates)

**Comment by agocorona** [comment]
Hi!

That different behaviour is not produced by wake, but by getCheckBoxes that
is defined that way: the first time it returns [] without any event. I
don't remember why....

see for example here:
http://tryplayg.herokuapp.com/try/widgets.hs/edit
the checkboxes example return []  inmediately

By the way you can force the evaluation of the next line of a monadic
expression anyway using an applicative operator: for example:

widget `wake`  onClick  <|> return whatever


the first time will return watever without waiting for the click


wake= fire= react= raiseEvent

2015-04-08 1:22 GMT+02:00 juicelink <notifications@github.com>:

> Hi,
>
> when I set console traces in todomvc exemple, I can see two different
> behaviors for the wake function
>
> in the newtodo function :
>
> newTodo= do
>       let entry= boxCell "new-todo"
>       task <- mk entry Nothing `wake` OnChange
>
> code after the wake line run only when the OnChange event is triggered
>
> in the toggleActive function:
>
>  toggleActive = do
>         Just (task,st) <- getTask idtask
>         let checked= case st of Completed -> True; Active -> False
>         let ch = setCheckBox checked "check" `wake` OnClick ! atr "class" "toggle"
>
> code after the the wake line is executed on Onclick event, but also the
> first time the function is called
>
> I can't figure why it differs and how to have the same behavior as in
> newtodo function (to avoid redondant local storage updates)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agocorona/hplayground/issues/8>.
>



-- 
Alberto.

**Comment by agocorona** [comment]
Hope that helps

2015-04-08 3:37 GMT+02:00 Alberto G. Corona <agocorona@gmail.com>:

> Hi!
>
> That different behaviour is not produced by wake, but by getCheckBoxes
> that is defined that way: the first time it returns [] without any event. I
> don't remember why....
>
> see for example here:
> http://tryplayg.herokuapp.com/try/widgets.hs/edit
> the checkboxes example return []  inmediately
>
> By the way you can force the evaluation of the next line of a monadic
> expression anyway using an applicative operator: for example:
>
> widget `wake`  onClick  <|> return whatever
>
>
> the first time will return watever without waiting for the click
>
>
> wake= fire= react= raiseEvent
>
> 2015-04-08 1:22 GMT+02:00 juicelink <notifications@github.com>:
>
>> Hi,
>>
>> when I set console traces in todomvc exemple, I can see two different
>> behaviors for the wake function
>>
>> in the newtodo function :
>>
>> newTodo= do
>>       let entry= boxCell "new-todo"
>>       task <- mk entry Nothing `wake` OnChange
>>
>> code after the wake line run only when the OnChange event is triggered
>>
>> in the toggleActive function:
>>
>>  toggleActive = do
>>         Just (task,st) <- getTask idtask
>>         let checked= case st of Completed -> True; Active -> False
>>         let ch = setCheckBox checked "check" `wake` OnClick ! atr "class" "toggle"
>>
>> code after the the wake line is executed on Onclick event, but also the
>> first time the function is called
>>
>> I can't figure why it differs and how to have the same behavior as in
>> newtodo function (to avoid redondant local storage updates)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/agocorona/hplayground/issues/8>.
>>
>
>
>
> --
> Alberto.
>



-- 
Alberto.

**Comment by juicelink** [comment]
thank you Alberto.

And if I want checkBox waiting for the click, is there a solution? Or Should I generate my input checkbox by another manner?

**Comment by juicelink** [comment]
I've written a new setCheckBox that seems to fill my constraints :

```
setCheckBox' :: (FormInput view,  MonadIO m) =>
                Bool -> String -> View view m  CheckBoxes
setCheckBox' checked v= View $ do
  st <- get
  put st{needForm= HasElems}
  n  <- genNewId
  me <- liftIO $ elemById n
  ret <- case me of
       Just e  -> liftIO $ getProp e "checked" >>= return . Just . CheckBoxes'
                       . (\c -> if c == "true" then [v] else [])
       _ ->  return Nothing

  return $ FormElm ( finput n "checkbox" v ( checked ) Nothing) ret
``` 

does it make sense?

the problem is that CheckBoxes constructor isn't exposed

**Comment by agocorona** [comment]
I just wrote this:

getCheckBoxes' cs= do
        r <- getCheckBoxes cs
        ev <- getEventData
        -- alert (evName ev)
        if evName ev /= "click" then stop else return r

It only filter the first event, the load event

empty=noWidget= stop.

2015-04-08 11:01 GMT+02:00 juicelink <notifications@github.com>:

> I've written a new setCheckBox that seems to fill my constraints :
>
> setCheckBox' :: (FormInput view,  MonadIO m) =>
>                 Bool -> String -> View view m  CheckBoxes
> setCheckBox' checked v= View $ do
>   st <- get
>   put st{needForm= HasElems}
>   n  <- genNewId
>   me <- liftIO $ elemById n
>   ret <- case me of
>        Just e  -> liftIO $ getProp e "checked" >>= return . Just . CheckBoxes'
>                        . (\c -> if c == "true" then [v] else [])
>        _ ->  return Nothing
>
>   return $ FormElm ( finput n "checkbox" v ( checked ) Nothing) ret
>
> does it make sense?
>
> the problem is that CheckBoxes constructor isn't exposed
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agocorona/hplayground/issues/8#issuecomment-90852642>.
>



-- 
Alberto.

**Comment by agocorona** [comment]
See it working here:

http://tryplayg.herokuapp.com/try/widgets-copy.hs/edit

2015-04-08 11:06 GMT+02:00 Alberto G. Corona <agocorona@gmail.com>:

> I just wrote this:
>
> getCheckBoxes' cs= do
>         r <- getCheckBoxes cs
>         ev <- getEventData
>         -- alert (evName ev)
>         if evName ev /= "click" then stop else return r
>
> It only filter the first event, the load event
>
> empty=noWidget= stop.
>
> 2015-04-08 11:01 GMT+02:00 juicelink <notifications@github.com>:
>
>> I've written a new setCheckBox that seems to fill my constraints :
>>
>> setCheckBox' :: (FormInput view,  MonadIO m) =>
>>                 Bool -> String -> View view m  CheckBoxes
>> setCheckBox' checked v= View $ do
>>   st <- get
>>   put st{needForm= HasElems}
>>   n  <- genNewId
>>   me <- liftIO $ elemById n
>>   ret <- case me of
>>        Just e  -> liftIO $ getProp e "checked" >>= return . Just . CheckBoxes'
>>                        . (\c -> if c == "true" then [v] else [])
>>        _ ->  return Nothing
>>
>>   return $ FormElm ( finput n "checkbox" v ( checked ) Nothing) ret
>>
>> does it make sense?
>>
>> the problem is that CheckBoxes constructor isn't exposed
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/agocorona/hplayground/issues/8#issuecomment-90852642>
>> .
>>
>
>
>
> --
> Alberto.
>



-- 
Alberto.

**Comment by juicelink** [comment]
Thanks!

**Comment by agocorona** [comment]
To complete the question and not confuse people:

unlike `pass`  the event set calls  `wake`, fire etc  do not block. `pass` return empty unless  the event desired arrives

`wake`, `fire` etc  simply execute the rest of the monadic computation when the event fires

when any event fires, it executes the continuation as much as it can, until some monadic statement return empty. So an event can execute code down including other statements that have event attached. 

So a widget can be called by the computation triggered by any event above it, not only the event that has attached directly to it.

the hplay widgets do not check the event that arrive, except `wbutton`, that use `pass`

when `main` is executed, the event associated with that execution is `"OnLoad"`.

if the widget has data, it return his value when the computation is executed by any event, no only  the one that is attached to it.

since for  getCheckBoxes  when  no check button pressed is valid data, it return  the empty list when main is executed.
